# Grahamwjohnon  
# Created Feb 2023

num_gpus: 2
 
# DATASET
continue_existing_training: True
cont_train_model_dir: '/media/glommy1/tornados/trained_models/dataset_train100.0_val0.0/ekaltadeta_Tue_Mar_25_16_49_04_2025' 
root_save_dir: '/media/glommy1/tornados' # Where the outputs of run will be stored
print_dataset_bargraphs: False # Rough visualization of all data timestamps/types for each patient. Slows down initialization. Typically set to False if not the first run of new model
pat_dir: '/media/graham/MOBO_RAID0/Ubuntu_Projects/SEEG_Tornados/preprocessed_data/Bipole_datasets/By_Channel_Scale/HistEqualScale/data_normalized_to_first_24_hours/wholeband/Mobo_pats' # parent directory where all pats data is stored
train_val_pat_perc: kwargs['train_val_pat_perc'] = [1.00, 0.0] # Will define patient level train/val split of datasets
pat_num_channels_LUT: '/media/graham/MOBO_RAID0/Ubuntu_Projects/SEEG_Tornados/data/pats_num_channels_LUT.csv'
num_samples: kwargs['num_samples'] = 1024*512 # Within each data pickle file
FS: 512             
atd_file: '/media/graham/MOBO_RAID0/Ubuntu_Projects/SEEG_Tornados/data/all_time_data_01092023_112957.csv'
data_dir_subfolder: '/scaled_data_epochs'
intrapatient_dataset_style: 2 # 1 all data (no SPES), 2 all data (with SPES), 3 ONLY SPES
train_hour_dataset_range: kwargs['train_hour_dataset_range'] = [-1, -1]  # [-1, -1] means all, [X, -1] means from X to end
rand_name_json: '/media/graham/MOBO_RAID0/Ubuntu_Projects/SEEG_Tornados/code2/utilities/animals.json'
num_dataloader_workers: 0 # persistent workers will be True if >0, IMPORTANT: DDP observed to be unstable if != 0
delete_old_checkpoints: True # Will only keep most recent checkpoint  
subprocess_num_threads: 1 

# RANDOM DATA GENERATOR - seperate subprocess
# This utilizes CPU/SSD resources to generate random batches even when plotting/saving etc.
# Default to put them directly into system RAM 
env_python_path: '/home/graham/anaconda3/envs/pytorch_env2/bin/python'
random_gen_script_path: '/media/graham/MOBO_RAID0/Ubuntu_Projects/SEEG_Tornados/code2/gen_random_data.py'
num_buffer_batches: kwargs['num_buffer_batches'] = int(kwargs['train_forward_passes'] / kwargs['num_gpus'])   # 512 # Max files to keep in random generator tmp directry 
num_data_threads: 1 # How many threads to start for each data generator (by each GPU)
nested_max_workers: 8 # For the get_batch subprocess

# POSTERIOR (a.k.a. Encoder)
encode_token_samples: 1 # Token size for encoder transformer
diag_mask_buffer_tokens: 16 # Left/Right how many tokens to mask off diagonal, so total masking is 2x this number along diagonal
padded_channels: 256 # input channels randomly padded up to this number to allow for different number of channels, this is the cross-attention dimension
crattn_num_heads: 8 # padding dimension / h = head dimension e.g. 256/8 = 32
crattn_num_layers: 16 
crattn_max_seq_len: kwargs['crattn_max_seq_len'] = kwargs['encode_token_samples']
crattn_dropout: 0.1 
transformer_dim: 1024 
transformer_seq_length: 512 # each ok these is 'padded_channels' x 'encode_token_samples' worth of data
max_seq_len: kwargs['max_seq_len'] = kwargs['transformer_seq_length']
max_batch_size: kwargs['max_batch_size'] = kwargs['random_pulls_in_batch'] * kwargs['inference_batch_mult']
n_layers: 16
n_heads: 32  # transformer_dim / n_heads = head dimension (e.g. 1024/32 = 32 head dimension)
multiple_of: 256 
ffn_dim_multiplier: 1.0 # Default is 1.0 to make FFN layers account for ~2/3 of total parameter count
attention_dropout: 0.1               
encoder_transformer_activation: "silu"
transformer_start_pos: 0 # Not currently coded up to work if > 0
top_dims: kwargs['top_dims'] = kwargs['transformer_dim'] # kwargs['num_encode_concat_transformer_tokens'] * kwargs['transformer_dim']
hidden_dims: 1024 # 4096
latent_dim: 1024 # 2048

posterior_mogpredictor_hidden_dim_list: [2048, 1024, 512] # Top should be approximately hidden dim of encoder, bottom bigger than prior_prior_mog_components to prevent bottlenecks
posterior_mogpredictor_dropout: 0.1

mse_weight_min: kwargs['mse_weight_min'] = 0
mse_weight_max: kwargs['mse_weight_max'] = 3
mse_weight_stall_epochs: 0
mse_weight_epochs_TO_max: 0
mse_weight_epochs_AT_max: 99999

LR_max_posterior: kwargs['LR_max_posterior'] = 1e-5 # 5e-7
LR_min_posterior: kwargs['LR_min_posterior'] = 1e-6 # 1e-8 
LR_epochs_stall_posterior: 0
LR_epochs_TO_max_posterior: 2
LR_epochs_AT_max_posterior: 2
manual_gamma_posterior: 0.25 # Will be applied to the LR_max & LR_min every 'manual_step_size'
manual_step_size_posterior: 99999
posterior_weight_decay: 0.1
adamW_beta1: 0.9
adamW_beta2: 0.95 

gumbel_softmax_temperature_max: 2.0 # Higher means softer assignment to MoG, lower temperature encourages component specialization
gumbel_softmax_temperature_min: 0.3 # Slightly higher than a typical 0.1 finish, higher final temp encourages rarer states to be able to use multiple components as their 'fingerprint' instead of ignoring them 
gumbel_softmax_temperature_stall_epochs: 100
gumbel_softmax_temperature_gamma: 0.99

posterior_mogpreds_entropy_weight_max: 0.5 # Encourages overall mogpred use to to be uniform across all inputs, i.e. don't let components die, encourage general components
posterior_mogpreds_entropy_weight_min: 0.5 # unstable/mode collapse if lowered too much, currently static
posterior_mogpreds_entropy_weight_stall_epochs: 99999
posterior_mogpreds_entropy_weight_taper_epochs: 99999

posterior_mogpreds_intersequence_diversity_weight_max: 0.1 # Encourages batchwise diveristy among mogpreds (otherwise entropy will just force uniform distribution)
posterior_mogpreds_intersequence_diversity_weight_min: 0.1 # unstable/mode collapse if lowered too much, currently static
posterior_mogpreds_intersequence_diversity_weight_stall_epochs: 99999
posterior_mogpreds_intersequence_diversity_weight_taper_epochs: 99999

# DECODER
decoder_base_dims: 4096 # top dim of decoder is [encode_token_samples * decoder_base_dims]
hash_output_range: kwargs['hash_output_range'] = (-5, 5)  # tuple, modify based on range of prior

# PRIOR (a.k.a. Mixture of Guassians, MoG)
prior_mog_components: 8 # Softmax sampling of components with gumbel-softmax trick
mean_lims: [-5, 5] # Make sure the prior's mean/logvars make sense with this limit
logvar_lims: [-3, 1] # Important to cap logvar on high end or KL divergence calculaton itself becomes unstable and will give very negative numbers
prior_initial_mean_spread: 3  # Uniform (e.g. value of 2 will be uniform [-2, 2])
prior_initial_logvar: 0 

prior_entropy_weight: kwargs['prior_entropy_weight'] = 1e-6 # Helps prevent mode collapse in PRIOR
prior_repulsion_weight: kwargs['prior_repulsion_weight'] = 1e-1 # Helps keep centers of PRIOR guassians far apart, need to scale with number of MoG components 

mean_match_static_weight: kwargs['mean_match_static_weight'] = 5e-3 # Essential for stability of posterior 
logvar_match_static_weight: kwargs['logvar_match_static_weight'] = 5e-2 # Essential for stability of posterior 

KL_divergence_max_weight: kwargs['KL_divergence_max_weight'] = 5e-4 # 2e-4 # With current architecture, 4096 dimensions, and 4 MoG components, very unstable if higher than 5e-4
KL_divergence_min_weight: kwargs['KL_divergence_min_weight'] = 0
KL_divergence_stall_epochs: 2 # Min KL_divergence weight rise until stall is complete
KL_divergence_epochs_AT_max: 50 
KL_divergence_epochs_TO_max: 25

LR_max_prior: kwargs['LR_max_prior'] = 1e-6
LR_min_prior: kwargs['LR_min_prior'] = 0
LR_epochs_stall_prior: 2 # Don't let it get whipped around while model posterior is getting established with baseline regularization (i.e. mean/logvar matching, entropy, diversity)
LR_epochs_TO_max_prior: 1
LR_epochs_AT_max_prior: 99999
manual_gamma_prior: 0.25 # Will be applied to the LR_max & LR_min every 'manual_step_size'
manual_step_size_prior: 99999
prior_weight_decay: 0.1
adamW_beta1_prior: 0.9
adamW_beta2_prior: 0.95

# GUASSIAN-PROCESS Prior (seperate from KL divergence of MoG for GM-VAE prior)
# Encourages token-to-token smoothness in latent space for sequential tokens
gp_sigma: 0.2 # Not quite sure what scale should be
gp_length_scale: kwargs['gp_length_scale'] = kwargs['diag_mask_buffer_tokens'] # Token-level kernel smoothing, setting to same scale as masking zone
gp_weight_max: kwargs['gp_weight_max'] = 1e-11 
gp_weight_min: kwargs['gp_weight_min'] = 0
gp_weight_stall_epochs: 40 # WWait for global latent structure to establish before smoothing small zones
gp_weight_epochs_AT_max: 50 
gp_weight_epochs_TO_max: 25

# CLASSIFIER - Adversarial
classifier_hidden_dims: [2048, 1024, 512]
classifier_num_pats: 45 #    ########   Hardcoded  ########
classifier_dropout: 0.1
classifier_weight: 1 # OVERALL ADVERSARIAL training: i.e. reverse gradient (VAE) AND classifier power. # Should probably get into same ballpark as recon and KL_divergence
classifier_alpha_max: kwargs['classifier_alpha_max'] = 1e-1 # Alpha of reverse gradient 
classifier_alpha_min: kwargs['classifier_alpha_min'] = 0 
classifier_epochs_AT_max: 99999
classifier_epochs_TO_max: 50
classifier_rise_first: True
LR_min_classifier: kwargs['LR_min_classifier'] = 1e-4 # 5e-7
classifier_weight_decay: 0
classifier_adamW_beta1: 0.9
classifier_adamW_beta2: 0.999

# TRAINING 
random_pulls_in_batch: 8 # BATCHSIZE
train_forward_passes: 1024 # Independent of batchsize, just random pulls of data
epochs_to_train: 300 
train_num_rand_hashes: kwargs['train_num_rand_hashes'] = 2**20  # Number of random channel orders per pat to input into encoder 
# Observed Phenonemon: Position of channels is learned somehow during encoding and embedded diffusely across latent dimensions, 
# Thus, no need for conditional decoding with unique hashing per channel order. Decoder just knows somehow, even with unseen patients. 

# VALIDATION
valfinetune_forward_passes: 2048 # Be mindful of data gen file buffer ('num_buffer_batches'), currently only based on train forward passes
valunseen_forward_passes: 2048 # Be mindful of data gen file buffer ('num_buffer_batches'), currently only based on train forward passes
val_finetine_bool: True # If False, will skip finetuning and just validate on unseen portion of validation patients 
val_every: 99999 # Will only do one epoch, so update 'valfinetune_forward_passes' if want to finetune longer
val_finetune_hour_dataset_range: kwargs['val_finetune_hour_dataset_range'] = [2, 50]
val_unseen_hour_dataset_range: kwargs['val_unseen_hour_dataset_range'] = [50, -1]
LR_val_gmvae: kwargs['LR_val_gmvae'] = 1e-7 # SHould probably set finetuning LR to about min of training LR if pulsing train LR, or down 1-2 orders of magnitude if train LR is constant (i.e. not pulsing)
LR_val_cls: kwargs['LR_val_cls'] = 1e-4
LR_val_prior: kwargs['LR_val_prior'] = kwargs['LR_val_gmvae']
val_num_rand_hashes: 1 # By having at 1, it limits the number of configs that model needs to finetune for a new patient

# INFERENCE
finetune_inference: False # If False, will just run inference on model trained on only 'train' patients
finetune_inference_epochs: -1 # NOTE: will  increase the epoch count overall to keep track of finetuning inference
inference_every: 99999
inference_batch_mult: 1 # Will enable higher inference throughput, but at cost of more VRAM at all times because max-batch_size needs to be increased for initialization of Transformer
inference_window_sec_list: [64, 64, 16, 16, 1] 
inference_stride_sec_list: [64, 16, 16, 4,  1] # Both window and stride must be multiple of input seconds to encoder,  (i.e. encode_token_samples * transformer_seq_length / FS)

# PLOTTING
total_collected_latents: 1024  # Currently just for plotting at the end of an epoch
singlebatch_latent_printing: True
num_singlebatch_channels_recon: 1 # Will be batch * this plotted
singlebatch_printing_interval_train: 64 
singlebatch_printing_interval_val: 64
num_recon_samples: 256 # this will limit how much is shown in recon plots, ERROR if not enough samples, pulls from START and END of transformer sequence 
num_rand_recon_plots: 4
num_singlebatch_dims: 5
num_accumulated_plotting_dims: 5
recent_display_iters: 5 # How often to print to console when training & how often to log to WandB


